@echo off

SET VS2019VC_DIR=C:\Program Files (x86)\Microsoft Visual Studio\2019
SET WDK_DIR=C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0
SET WINDDK_DIR=C:\WinDDK\7600.16385.1\bin\amd64

SET DEFAULT_DIR=C:\VBoxBuild

SET MINGW_DIR=%DEFAULT_DIR%\MinGW\mingw64
SET SDL_DIR=%DEFAULT_DIR%\SDL
SET SSL64_DIR=%DEFAULT_DIR%\SSL\OpenSSL-Win64
SET SSL32_DIR=%DEFAULT_DIR%\SSL\OpenSSL-Win32
SET CURL_DIR=%DEFAULT_DIR%\curl\curl-7.64.1
SET QT_DIR=%DEFAULT_DIR%\Qt\qt-everywhere-src-5.14.2
SET QT_BUILD_DIR=%DEFAULT_DIR%\Qt\qt5-x64
SET VBOX_DIR=%DEFAULT_DIR%\VirtualBox
